### ISSUE TITLE
Investigate if/why settings are not applied.

### ISSUE THREAD

**Issue by tomaszpoliszuk** [tomaszpoliszuk/ActivatorListenerForPowercuff#3]
> I have installed your tweak but l’m pretty sure it’s not working as it should.
>
> The problem is that although it changes the powercuff settings successfully, powercuff itself doesn’t apply the new setting automatically. To make powercuff recognise the change I have to open it’s setting page and reselect the throttling mode, making the tweak useless.
>
> I have two methods to test the current throttling setting: * Charging current is lowered on moderate and heavy, I actually use this pretty often to control the charge time * On heavy my screen starts to stutter making it noticeable

https://old.reddit.com/r/jailbreak/comments/hbd9tb/update_open_source_activator_listener_for/g9av3ce/?context=3

**Comment by MJavad** [comment]
Any progress on this?

**Comment by tomaszpoliszuk** [comment]
Sorry - I was occupied with other things - today i've started looking at all my tweaks.

Could you check this way:

- check current Powercuff settings,
- close Settings app
- assign activator action (other than current Powercuff settings),
- run it,
- check current Powercuff settings again

The reason i'm asking this is that if you change settings while Powercuff settings are open you will see no change but after reopening settings you should see that it changed (at least that was happening on my devices).

Let me know of your findings :)

**Comment by CySxL** [comment]
yes, I have the same problem.

I've do ur checking, and yes the setting of Powercuff is changed.

But the Only in Low Power Mode toggle would automatically be disabled.

My workaround is :
using Activator to set automatically enable LPM while in lockscreen and disable LPM while unlock device.
and also let Powercuff(moderate) enable Only In Low Power Mode.

I wanna set Activator listener for powercuff to disable Powercuff (Throttling set to None) while in lockscreen and connecting to charger, and enable Powercuff as moderate state while in lockscreen but disconnect the charger.


But the result is Powercuff throttling will stay at "moderate" even if I unlock my device, guess that's caused by the "Only In LPM" toggle is disabled in Powercuff.

**Comment by tomaszpoliszuk** [comment]
OK, I will dig into Powercuff source code and try my best to fix this issue

**Comment by CySxL** [comment]
Appreciate !! Please take ur tIme, no rush at all :)

**Comment by tomaszpoliszuk** [comment]
Just letting you know that I confirm this issue and I don't know yet how to fix it but i will do everything in my power to do it :)

**Comment by tomaszpoliszuk** [comment]
Sorry for too long delay :/

Tweak is now updated to version 1.0.2 that fixes this issue.

Grab it from [Releases Page](https://github.com/tomaszpoliszuk/ActivatorListenerForPowercuff/releases) - [Direct link to deb file](https://github.com/tomaszpoliszuk/ActivatorListenerForPowercuff/releases/download/1.0.2/com.tomaszpoliszuk.activatorlistenerforpowercuff_1.0.2_iphoneos-arm.deb)
