### ISSUE TITLE
Please, can add it?

### ISSUE THREAD

**Issue by lucaszhaoting** [tomaszpoliszuk/ActivatorListenerForPowercuff#5]
I love your tweaks, i want to ask, if can add just dont disable the only lpm?
so dont disable that toggles, thanks

**Comment by tomaszpoliszuk** [comment]
Sorry for very late response :(
While creating this listeners I've decided to always turn off only lpm.
This is intentional to prevent situations when this Listener triggers but nothing happens because device is not in low power mode.
But you can use additional [Low Power Mode Events for Activator](http://cydia.saurik.com/package/com.tomaszpoliszuk.lowpowermodeeventsforactivator/) to control Powercuff when Low Power Mode changes (this way you can set different modes for low/default power modes).

Tweak is now updated to version 1.0.2.

Grab it from [Releases Page](https://github.com/tomaszpoliszuk/ActivatorListenerForPowercuff/releases) - [Direct link to deb file](https://github.com/tomaszpoliszuk/ActivatorListenerForPowercuff/releases/download/1.0.2/com.tomaszpoliszuk.activatorlistenerforpowercuff_1.0.2_iphoneos-arm.deb)

I'm closing this issue but feel free to reopen or comment if you have additional questions.
